# v3 syntax
version: '3.7'

# Networks
networks:
  joomla:
    name: joomla
    driver: bridge

services:
  database:
    image: mysql:5.7
    container_name: joomladb
    networks:
      - joomla
    environment:
      - "MYSQL_DATABASE=joomla"
      - "MYSQL_PASSWORD=joomla"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:33060"
  # The Application
  app:
    image: joomla
    container_name: joomla
    networks:
      - joomla
    environment:
      - "JOOMLA_DB_HOST=joomladb"
      - "JOOMLA_DB_NAME=joomla"
      - "JOOMLA_DB_PASSWORD=secret"
    ports:
      - "8080:80"
    depends_on:
      - database